name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["ezntek/beancode"]
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling out this bug report.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you do to trigger the issue? What was the expected behavior?
      value: "I was programming, and my code spontaneously combusted and turned into a marshmallow!"
    validations:
      required: true
  - type: textarea
    id: version-info
    attributes:
      label: Version Info
      description: Which version and commit of beancode-web were you running?  
      value: "Click the info (i) button on the top right corner, and paste all the version info in the table here."
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Which browser did this issue occur on?
      multiple: true
      options:
        - Firefox (or Firefox-based)
        - Chromium (Chrome, Brave, Opera, Edge, or other Chromium-based)
        - Safari
        - Other (specify in the description)
